### ISSUE TITLE
Getting started page - mistakes

### ISSUE THREAD

**Issue by poszke** [slamby/slamby-website#19]
API Activation:
For open-source license, **your** can request one from the setup wizard directly

**Comment by petermezei** [comment]
Its worth to create printscreen and highlight where the issue located, like this

![image](https://cloud.githubusercontent.com/assets/18461114/21222609/f629d2ea-c2c2-11e6-8fcf-4a2a4db78699.png)

**Comment by petermezei** [comment]
Solved this issue

**Comment by petermezei** [comment]
Closed this issue #19

**Comment by petermezei** [comment]
Fixes #19
