### ISSUE TITLE
TAU Page Image Problems

### ISSUE THREAD

**Issue by OrselSani** [slamby/slamby-website#7]
![image](https://cloud.githubusercontent.com/assets/18461540/18276480/69499f56-744b-11e6-8a08-73605bdb9a90.png)

![image](https://cloud.githubusercontent.com/assets/18461540/18276488/744b1fd8-744b-11e6-9809-35d28454c58a.png)

**Comment by attilalaszlo** [comment]
fixed (thanks for the images @OrselSani )
