### ISSUE TITLE
Simple Adjust Suggestions

### ISSUE THREAD

**Issue by OrselSani** [slamby/slamby-website#8]
![image](https://cloud.githubusercontent.com/assets/18461540/18662109/20bc1fd8-7f19-11e6-8987-66a03de85e96.png)

When clicked to the "For Developers" from the header menu, developer site should be opened in a new tab. 

And as a reminder, we can add pinterest icon to the footer menu https://www.pinterest.com/slambynews/

**Comment by petermezei** [comment]
Fixed, added.
